name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    if: github.repository == 'Vincent0700/awtrix-simulator'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout repos
        uses: actions/checkout@main

      - name: Setup NodeJs
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build codes
        run: |
          npm install
          npm run build

      - name: Push to gh-pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.REPO_ACTIONS_TOKEN }}
